#![forbid(unsafe_code)]

// All fn code not main() or safely_get_fnaddr_from_got() is from
// cve-rs (https://github.com/Speykious/cve-rs), which uses a
// "soundness" issue in Rust (known since 2015) that
// allows for type punning actually less strict than C's.

// I have put what I needed from cve-rs all in this one file to
// emphasize that only nominally "safe" Rust (i.e. Rust without
// any `unsafe` statements/blocks or std::ffi use) is needed to gain
// arbitrary access to glibc (and a few Linux API) functions,
// pointer arithmetic, and anything C can do.

/// This function, on its own, is sound:
/// - `_val_a`'s lifetime is `&'a &'b`. This means that `'b` must outlive `'a`, so
///   that the `'a` reference is never dangling. If `'a` outlived `'b` then it could
///   borrow data that's already been dropped.
/// - Therefore, `val_b`, which has a lifetime of `'b`, is valid for `'a`.
#[inline(never)]
pub const fn lifetime_translator<'a, 'b, T: ?Sized>(_val_a: &'a &'b (), val_b: &'b T) -> &'a T {
    val_b
}

/// This does the same thing as [`lifetime_translator`], just for mutable refs.
#[inline(never)]
pub fn lifetime_translator_mut<'a, 'b, T: ?Sized>(
    _val_a: &'a &'b (),
    val_b: &'b mut T,
) -> &'a mut T {
    val_b
}

/// Expands the domain of `'a` to `'b`.
///
/// # Safety
///
/// Safety? What's that?
pub fn expand<'a, 'b, T: ?Sized>(x: &'a T) -> &'b T {
    let f: for<'x> fn(_, &'x T) -> &'b T = lifetime_translator;
    f(STATIC_UNIT, x)
}

/// This does the same thing as [`expand`] for mutable references.
///
/// # Safety
///
/// Safety? What's that?
pub fn expand_mut<'a, 'b, T: ?Sized>(x: &'a mut T) -> &'b mut T {
    let f: for<'x> fn(_, &'x mut T) -> &'b mut T = lifetime_translator_mut;
    f(STATIC_UNIT, x)
}

/// A unit with a static lifetime.
///
/// Thanks to the soundness hole, this lets us cast any value all the way up to
/// a `'static` lifetime, meaning any lifetime we want.
pub const STATIC_UNIT: &&() = &&();

pub fn transmute<A, B>(obj: A) -> B {
    use std::hint::black_box;

    // The layout of `DummyEnum` is approximately
    // DummyEnum {
    //     is_a_or_b: u8,
    //     data: usize,
    // }
    // Note that `data` is shared between `DummyEnum::A` and `DummyEnum::B`.
    // This should hopefully be more reliable than spamming the stack with a value and hoping the memory
    // is placed correctly by the compiler.
    #[allow(dead_code)]
    enum DummyEnum<A, B> {
        A(Option<Box<A>>),
        B(Option<Box<B>>),
    }

    #[inline(never)]
    fn transmute_inner<A, B>(dummy: &mut DummyEnum<A, B>, obj: A) -> B {
        let DummyEnum::B(ref_to_b) = dummy else {
            unreachable!()
        };
        let ref_to_b = expand_mut(ref_to_b);
        *dummy = DummyEnum::A(Some(Box::new(obj)));
        black_box(dummy);

        *ref_to_b.take().unwrap()
    }

    transmute_inner(black_box(&mut DummyEnum::B(None)), obj)
}

/// This function works only with JMP/CALL instructions
/// which have an encoded 4 byte offset and probably only with
/// x86_64 ELF bins. The PLT stubs would obv be irrelevant to PE bins
fn safely_get_fnaddr_from_got<FnType>(needle: &[u8]) -> Option<FnType> {
    let mainaddr = transmute::<fn() -> (), usize>(main);
    let mem = transmute::<usize, &[u8; u32::MAX as usize]>(mainaddr);

    if let Some(position) = mem
        .windows(needle.len())
        .position(|window| window == needle)
    {
        let plt_offset_offset: usize = position + needle.len();
        let offsetslice = &mem[plt_offset_offset..plt_offset_offset + 4];

        let signed_offset: i32 = (offsetslice[0] as i32)
            | (offsetslice[1] as i32) << (1 << 3)
            | (offsetslice[2] as i32) << (2 << 3)
            | (offsetslice[3] as i32) << (3 << 3);

        //The 4-byte offset encoded in the CALL opcode is relative to the next instruction's address
        let next_op_addr: usize = mainaddr + plt_offset_offset + 4;
        let call_addr_operand_addr: usize = (signed_offset as i64 + next_op_addr as i64) as usize;
        let got_entry_addr = transmute::<usize, &[u8; 8]>(call_addr_operand_addr);
        let target_be: usize = usize::from_le_bytes(*got_entry_addr);

        let safe_fn = transmute::<usize, FnType>(target_be);
        
        return Some(safe_fn);
    } else {
        println!("PLT stub not found!");
    }
    None
}

/// Safely get safe versions of C stdlib memset, malloc, and free by searching
/// instruction memory for PLT stubs that have opcodes with the GOT addresses encoded.
/// This is non-portable but works for the debug and release x86_64 ELF binaries
/// generated by whatever versions of glibc and rustc are on my machine.
fn main() {
	
// This is not shellcode, but the contents of the PLT stubs which
// call these functions. Their JMP and CALL instructions have, encoded,
// the addresses of their functions' GOT entries, at which there are
// stored the actual callable addresses. These are populated at load.

    use std::hint::black_box;
    let memset_stub = black_box(&[0x4c, 0x89, 0xf7, 0x31, 0xf6, 0x48, 0x89, 0xda, 0xff, 0x15]);
    let malloc_stub = &[0x48, 0x89, 0xd7, 0xff, 0x25];
    let free_stub = &[0x4c, 0x89, 0xf7, 0xff, 0x15];
    let mmap64_stub = black_box(&[0x45, 0x89, 0xf0, 0x45, 0x31, 0xc9, 0xff, 0x15]);
    let munmap_stub = black_box(&[0x4c, 0x89, 0xef, 0x4c, 0x89, 0xe6, 0xff, 0x15]);

    let safe_memset = match safely_get_fnaddr_from_plt::<fn(usize, i32, usize)>(memset_stub) {
        Some(val) => val,
        None => {
            println!("Could not find memset");
            return;
        }
    };

    let safe_malloc = match safely_get_fnaddr_from_plt::<fn(usize) -> usize>(malloc_stub) {
        Some(val) => val,
        None => {
            println!("Could not find malloc");
            return;
        }
    };

    let safe_free = match safely_get_fnaddr_from_plt::<fn(usize) -> ()>(free_stub) {
        Some(val) => val,
        None => {
            println!("Could not find free");
            return;
        }
    };

    let safe_mmap64 = match safely_get_fnaddr_from_plt::<
        fn(usize, usize, i32, i32, i32, isize) -> isize,
    >(mmap64_stub)
    {
        Some(val) => val,
        None => {
            println!("Could not find mmap64");
            return;
        }
    };

    let safe_munmap = match safely_get_fnaddr_from_plt::<fn(usize, usize) -> i32>(munmap_stub) {
        Some(val) => val,
        None => {
            println!("Could not find munmap");
            return;
        }
    };

    let pheapmem = safe_malloc(64);
    let heapslice = transmute::<usize, &mut [u8; 64]>(pheapmem);

    println!("\nHeapslice Contents:");
    for idx in 0..64 {
        print!("0x{:x}{}", heapslice[idx],
        if idx == 63 {"\n"} else {","});
    }

    safe_memset(pheapmem, 0x42, 64);

    println!("\nAllocated heap contents after memset:");
    for idx in 0..64 {
        print!("0x{:x}{}", heapslice[idx],
        if idx == 63 {"\n"} else {","});
        heapslice[idx] = ((idx << 1) & 255) as u8;
    }

    println!("\nAllocated heap contents after writing:");
    for idx in 0..64 {
        print!("0x{:x}{}", heapslice[idx],
        if idx == 63 {"\n"} else {","});
    }

    print!("\n");

    let rval = safe_mmap64(0, 512, 7, 34, -1, 0);

    if rval < 0 {
        println!("safe_mmap64 failed.");
    } else {
        let quote_shellcode_unquote: &[u8] = &[
            0x55, //push qword rbp
            0x53, //push qword rbx
            0x48, 0x89, 0xE5, //mov rbp, rsp
            0x48, 0x83, 0xec, 0x20, //sub rsp, qword 20h
            0xb8, 0x1, 0x00, 0x00, 0x00, //mov rax, 1
            0xbf, 0x01, 0x00, 0x00, 0x00, //mov rdi, 1
            0x48, 0x8d, 0x35, 0xf, 0x00, 0x00, 0x00, //lea rsi, [strlabel]
            0xba, 0x1f, 0x00, 0x00, 0x00, //mov rdx, 31
            0xf, 0x05, //syscall (write string at strlabel)
            0x48, 0x89, 0xec, //mov rsp, rbp
            0x5b, //pop qword rbx
            0x5d, //pop qword rbp
            0xc3, //ret
            //strlabel:
            0xeb, 0xfe, 0x52, 0x75, 0x73, 0x74, 0x20, 0x69, 0x73, 0x20, 0x61, 0x20, 0x6e, 0x65,
            0x77, 0x20, 0x74, 0x79, 0x70, 0x65, 0x20, 0x6f, 0x66, 0x20, 0x6c, 0x61, 0x6e, 0x67,
            0x75, 0x61, 0x67, 0x65, 0xa
        ];
        println!("safe_mmap64 returned 0x{:x} marked rwx", rval);

        let rwxmem = transmute::<isize, &mut [u8; 512]>(rval);
        for idx in 0..quote_shellcode_unquote.len() {
            rwxmem[idx] = quote_shellcode_unquote[idx];
        }

        let fp = transmute::<&mut [u8; 512], fn() -> ()>(rwxmem);
        fp();

        let munmap_result = safe_munmap(rval as usize, 512);
        if munmap_result < 0 {
            println!("munmap() failed");
        }
    }

    safe_free(pheapmem);
}
