#![forbid(unsafe_code)]

use std::convert::TryInto;

/* All code above fn main() from cve-rs (https://github.com/Speykious/cve-rs).
 * I have put it all in one file to emphasize that only standard Rust is used
 * */

/// This function, on its own, is sound:
/// - `_val_a`'s lifetime is `&'a &'b`. This means that `'b` must outlive `'a`, so
///   that the `'a` reference is never dangling. If `'a` outlived `'b` then it could
///   borrow data that's already been dropped.
/// - Therefore, `val_b`, which has a lifetime of `'b`, is valid for `'a`.
#[inline(never)]
pub const fn lifetime_translator<'a, 'b, T: ?Sized>(_val_a: &'a &'b (), val_b: &'b T) -> &'a T {
    val_b
}

/// This does the same thing as [`lifetime_translator`], just for mutable refs.
#[inline(never)]
pub fn lifetime_translator_mut<'a, 'b, T: ?Sized>(
    _val_a: &'a &'b (),
    val_b: &'b mut T,
) -> &'a mut T {
    val_b
}

/// Expands the domain of `'a` to `'b`.
///
/// # Safety
///
/// Safety? What's that?
pub fn expand<'a, 'b, T: ?Sized>(x: &'a T) -> &'b T {
    let f: for<'x> fn(_, &'x T) -> &'b T = lifetime_translator;
    f(STATIC_UNIT, x)
}

/// This does the same thing as [`expand`] for mutable references.
///
/// # Safety
///
/// Safety? What's that?
pub fn expand_mut<'a, 'b, T: ?Sized>(x: &'a mut T) -> &'b mut T {
    let f: for<'x> fn(_, &'x mut T) -> &'b mut T = lifetime_translator_mut;
    f(STATIC_UNIT, x)
}

/// A unit with a static lifetime.
///
/// Thanks to the soundness hole, this lets us cast any value all the way up to
/// a `'static` lifetime, meaning any lifetime we want.
pub const STATIC_UNIT: &&() = &&();

pub fn transmute<A, B>(obj: A) -> B {
    use std::hint::black_box;

    // The layout of `DummyEnum` is approximately
    // DummyEnum {
    //     is_a_or_b: u8,
    //     data: usize,
    // }
    // Note that `data` is shared between `DummyEnum::A` and `DummyEnum::B`.
    // This should hopefully be more reliable than spamming the stack with a value and hoping the memory
    // is placed correctly by the compiler.
    #[allow(dead_code)]
    enum DummyEnum<A, B> {
        A(Option<Box<A>>),
        B(Option<Box<B>>),
    }

    #[inline(never)]
    fn transmute_inner<A, B>(dummy: &mut DummyEnum<A, B>, obj: A) -> B {
        let DummyEnum::B(ref_to_b) = dummy else {
            unreachable!()
        };
        let ref_to_b = expand_mut(ref_to_b);
        *dummy = DummyEnum::A(Some(Box::new(obj)));
        black_box(dummy);

        *ref_to_b.take().unwrap()
    }

    transmute_inner(black_box(&mut DummyEnum::B(None)), obj)
}

/// This specific function works only with JMP/CALL instructions
/// which have an encoded 4 byte offset and on x86_64 ELF bins, though
/// possibly not even a large subset of those
fn safely_get_fnaddr_from_plt<FnType>(needle: &[u8]) -> Option<FnType> {
    let mainaddr = transmute::<fn() -> (), usize>(main);
    let mem = transmute::<usize, &[u8; u32::MAX as usize]>(mainaddr);

    /* This technique should work for any function imported by the rust stdlib, though
     * can need adjustment depending on where the stub is relative to main, which
     * I think can change depending on ASLR among many other things.
     * It would need to be modified to work on PE bins*/

    if let Some(position) = mem
        .windows(needle.len())
        .position(|window| window == needle)
    {
        let plt_offset_offset: usize = position + needle.len();
        let offsetslice = &mem[plt_offset_offset..plt_offset_offset + 4];

        let offset = u32::from_le_bytes(match offsetslice.try_into() {
            Ok(val) => val,
            Err(err) => {
                println!("Error: {}", err);
                return None;
            }
        });

        //The 4-byte offset encoded in the CALL opcode is relative to the next instruction's address
        let next_op_addr: usize = mainaddr + plt_offset_offset + 4;
        let call_addr_operand_addr: usize = offset as usize + next_op_addr;
        let plt_entry_addr = transmute::<usize, &[u8; 8]>(call_addr_operand_addr);
        let target_be: usize = usize::from_le_bytes(*plt_entry_addr);

        let safe_fn = transmute::<usize, FnType>(target_be);
        return Some(safe_fn);
    } else {
        println!("PLT stub not found!");
    }
    None
}

/// Safely get safe versions of C stdlib memset, malloc, and free by searching
/// instruction memory for opcodes with the PLT addresses encoded.
/// This is non-portable but works for the debug and release x86_64 ELF binaries
/// generated by whatever versions of glibc and rustc are on my machine.

/// Safely dumps core by double freeing after completion to demonstrate
/// that the first call to free() did in fact free
fn main() {
	/* This is not shellcode, but the contents of the stubs which
	 * call these functions. Their JMP and CALL instructions have
	 * the address of the function's PLT entry, which we can use
	 * to compute their callable addresses */
	 
	let memset_stub = &[0x4c, 0x89, 0xf7, 0x31, 0xf6, 0x48, 0x89, 0xda, 0xff, 0x15];
	let malloc_stub = &[0x48, 0x89, 0xd7, 0xff, 0x25];
	let free_stub = &[0x4c, 0x89, 0xf7, 0xff, 0x15];
	
    let safe_memset = safely_get_fnaddr_from_plt::<extern "C" fn(usize, i32, usize)>(memset_stub)
    .unwrap();
    let safe_malloc =
        safely_get_fnaddr_from_plt::<extern "C" fn(usize) -> usize>(malloc_stub).unwrap();
    let safe_free =
        safely_get_fnaddr_from_plt::<extern "C" fn(usize) -> ()>(free_stub).unwrap();

    let pheapmem = safe_malloc(64);

    let heapslice = transmute::<usize, &mut [u8; 64]>(pheapmem);

    let pheapslice = transmute::<&mut [u8], usize>(heapslice);
    let ppheapslice = transmute::<usize, &mut [u8; 64]>(pheapslice);

    println!("\nHeapslice Contents:");
    for idx in 0..64 {
        print!("0x{:x},", ppheapslice[idx]);
    }

    safe_memset(pheapmem, 0x69, 64);

    println!("\nAllocated heap contents after memset:");
    for idx in 0..64 {
        print!("0x{:x},", heapslice[idx]);
        heapslice[idx] = ((idx << 1) & 255) as u8;
    }

    println!("\nAllocated heap contents after writing:");
    for idx in 0..64 {
        print!("0x{:x},", heapslice[idx]);
    }

    print!("\n");

    safe_free(pheapmem);
    // Safely double free and cause a blazingly fast core dump
    safe_free(pheapmem);
}
